services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes:
      - .:/usr/src/app
      - jekyll-gems:/usr/local/bundle  # Persist gems here
    ports:
      - "4000:4000"
    user: 1000:1000
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --config _config.yml,_config_dev.yml

volumes:
  jekyll-gems:
